# Generated by Django 4.0.6 on 2022-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedtodirectory',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
