# Generated by Django 4.0.6 on 2022-08-13 22:01

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_allowedtodirectory_can_add_delete_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.FileField(upload_to=mainapp.models.when_upload_file),
        ),
    ]
